box_memory: 4096
box_cpus: 2
box_cpu_max_exec_cap: "90"
disksize: "40GB"
ip_address: "192.168.1.100"
host_network: ~ # If vagrant ask for a network device, you may define it's label here.
ca_certificates: ~ # Set to a glob expression where CA certificates are stored (C:/Users/USER/.ca-certificates/{GFI*.crt,*.local.crt})
ssh:
  username: vagrant
synced_folders:
## Configure folders to share here
## Use this naming convention to match docker for windows and allow docker PHPStorm support
#  user:
#    source: 'C:\Users\user' # absolute or relative path from Vagrantfile
#    target: '/c/Users/user' # absolute or relative path from home of VM
#  projects:
#    source: 'C:\devel\projects' # absolute or relative path from Vagrantfile
#    target: '/c/devel/projects' # absolute or relative path from home of VM
