box_memory: 4096
box_cpus: 2
box_cpu_max_exec_cap: "90"
disksize: "40GB"
ip_address: "192.168.1.100"
host_network: ~ # Si vagrant demande sur quelle carte attacher le réseau, définir le libellé de la carte ici.
ssh:
  username: vagrant
  #password: vagrant
#synced_folders:
## Configurer les dossiers à synchroniser ici
#  test:
#    source: "C:\\test"
#    target: "test" # dossier relatif au home du user utilisé pour la connexion ssh (voir paramètre du yml ssh.username)
## Utiliser ces partages permet l'utilisation du plugin docker sur PHPStorm (patterns Docker for windows)
#  d_user:
#    source: 'D:\Users\FRUP67305'
#    target: '/d/Users/FRUP67305'
#  c_projects:
#    source: 'C:\devel\projects'
#    target: '/c/devel/projects'
